server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounting
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  springdoc:
    api-docs:
      enabled: true
      path: /api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      display-request-duration: true
      groups-order: DESC
      operations-sorter: method
      disable-swagger-default-url: true
      use-root-path: true
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json